name: Run tests (macos/x86_64)
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: make

      - name: Test
        run: make test
