name: macOS/arm64
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    # According to the link below, macos-lates runs on Apple Silicon
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: make

      - name: Test
        run: make test
